The data collection phase was succesful.  Now it is time to clean the data, after looking at the CSV file,
there are some changes need on how the country was saved ES to Spain.

In [1]:
import pandas as pd 


breakers_raw = pd.read_csv('C:\\ironhack\\labs\\breaker-detection-project\\data\\data\\breaker_dataset.csv')

In [2]:
breakers = breakers_raw.copy()

In [3]:
breakers.head()

,filename,timestamp,country,panel_age,phase_type,has_rcd,has_rcd_si,has_iga,iga_amp,has_ovp,mcb_values,num_mcbs,comments,number_rcd
0,08991740-04c2-4925-8fbf-27c878867339.jpg,2026-03-05T23:35:37,ES,15 años,1,1,1,0.0,0,0,"10,16,20,20",4,Hard to read mcb_value,1
1,08bf2ea5-6c4b-4fe4-8c6e-368e5bf3a025.jpg,2026-03-05T23:35:50,ES,5-10 años,1,1,0,1.0,25,0,"10,16,16",3,4,1
2,09f51da3-4395-46a1-858b-69fd2a973ed4.jpg,2026-03-05T23:36:12,ES,10-15 años,3,1,1,1.0,80,0,"6,6,10,10,10,10,16,16,20,20,20,25,25,25,32",15,13,5
3,132bb9c5-82d5-477d-9cf8-2901e936bd47.jpg,2026-03-05T23:36:26,ES,15 años,1,1,0,1.0,32,0,"10,16,20,25",4,4,1
4,163d9435-108a-48bb-a864-46e40d2aa6b6.jpg,2026-03-05T23:36:38,ES,> 20 years,1,1,0,1.0,32,0,"10,15,20,25",4,4,1

In [4]:
# Replace ES with SPAIN
breakers['country'] = breakers['country'].replace('ES','SPAIN')
breakers.head()

,filename,timestamp,country,panel_age,phase_type,has_rcd,has_rcd_si,has_iga,iga_amp,has_ovp,mcb_values,num_mcbs,comments,number_rcd
0,08991740-04c2-4925-8fbf-27c878867339.jpg,2026-03-05T23:35:37,SPAIN,15 años,1,1,1,0.0,0,0,"10,16,20,20",4,Hard to read mcb_value,1
1,08bf2ea5-6c4b-4fe4-8c6e-368e5bf3a025.jpg,2026-03-05T23:35:50,SPAIN,5-10 años,1,1,0,1.0,25,0,"10,16,16",3,4,1
2,09f51da3-4395-46a1-858b-69fd2a973ed4.jpg,2026-03-05T23:36:12,SPAIN,10-15 años,3,1,1,1.0,80,0,"6,6,10,10,10,10,16,16,20,20,20,25,25,25,32",15,13,5
3,132bb9c5-82d5-477d-9cf8-2901e936bd47.jpg,2026-03-05T23:36:26,SPAIN,15 años,1,1,0,1.0,32,0,"10,16,20,25",4,4,1
4,163d9435-108a-48bb-a864-46e40d2aa6b6.jpg,2026-03-05T23:36:38,SPAIN,> 20 years,1,1,0,1.0,32,0,"10,15,20,25",4,4,1

In [5]:
# Replace años with years
breakers['panel_age']= breakers['panel_age'].str.replace('años','years')

breakers.head()

,filename,timestamp,country,panel_age,phase_type,has_rcd,has_rcd_si,has_iga,iga_amp,has_ovp,mcb_values,num_mcbs,comments,number_rcd
0,08991740-04c2-4925-8fbf-27c878867339.jpg,2026-03-05T23:35:37,SPAIN,15 years,1,1,1,0.0,0,0,"10,16,20,20",4,Hard to read mcb_value,1
1,08bf2ea5-6c4b-4fe4-8c6e-368e5bf3a025.jpg,2026-03-05T23:35:50,SPAIN,5-10 years,1,1,0,1.0,25,0,"10,16,16",3,4,1
2,09f51da3-4395-46a1-858b-69fd2a973ed4.jpg,2026-03-05T23:36:12,SPAIN,10-15 years,3,1,1,1.0,80,0,"6,6,10,10,10,10,16,16,20,20,20,25,25,25,32",15,13,5
3,132bb9c5-82d5-477d-9cf8-2901e936bd47.jpg,2026-03-05T23:36:26,SPAIN,15 years,1,1,0,1.0,32,0,"10,16,20,25",4,4,1
4,163d9435-108a-48bb-a864-46e40d2aa6b6.jpg,2026-03-05T23:36:38,SPAIN,> 20 years,1,1,0,1.0,32,0,"10,15,20,25",4,4,1

In [6]:
# drop row where there are many NA due to a bad image that was unreadable by the labeler
breakers = breakers[breakers['filename'] != '08991740-04c2-4925-8fbf-27c878867339.jpg']

In [7]:
#change timestamps to datatime
breakers['timestamp'] = pd.to_datetime(breakers['timestamp'])

In [8]:
#convert all columns that start with has from floats to ints
has_cols = [c for c in breakers.columns if c.startswith('has_')]

breakers[has_cols] = breakers[has_cols].fillna(0).astype(int)

In [9]:
print(breakers.dtypes)

filename                 str
timestamp     datetime64[us]
country                  str
panel_age                str
phase_type             int64
has_rcd                int64
has_rcd_si             int64
has_iga                int64
iga_amp                int64
has_ovp                int64
mcb_values               str
num_mcbs               int64
comments                 str
number_rcd             int64
dtype: object

In [10]:
# convert strings from mcb_values so math can be performed on amparage values
breakers['mcb_values'] = breakers['mcb_values'].apply(lambda x: [int(v) for v in str(x).split(',') if v.strip().isdigit()])

In [11]:
# change iga_amp from float to int
breakers['iga_amp'] = breakers['iga_amp'].fillna(0).astype(int)

In [12]:
print(breakers.dtypes)

filename                 str
timestamp     datetime64[us]
country                  str
panel_age                str
phase_type             int64
has_rcd                int64
has_rcd_si             int64
has_iga                int64
iga_amp                int64
has_ovp                int64
mcb_values            object
num_mcbs               int64
comments                 str
number_rcd             int64
dtype: object

In [14]:
import matplotlib.pyplot as plt 
import seaborn as sns   

sns.set_theme(style='whitegrid')

In [16]:
# Calculate counts
ovp_counts = breakers['has_ovp'].value_counts()
ovp_percentages = breakers['has_ovp'].value_counts(normalize=True) * 100

# Create a summary dataframe for easy viewing
ovp_summary = pd.DataFrame({
    'Count': ovp_counts,
    'Percentage': ovp_percentages
})

# Map the index to be more descriptive
ovp_summary.index = ovp_summary.index.map({1: 'Has OVP (Safe)', 0: 'Lacks OVP (Unsafe)'})

print("Overall OVP Distribution:")
print(ovp_summary)
print("\nTotal panels analyzed:", len(breakers))

Overall OVP Distribution:
                    Count  Percentage
has_ovp
Lacks OVP (Unsafe)     46   90.196078
Has OVP (Safe)          5    9.803922

Total panels analyzed: 51